version: "3"

services:

  frontend:
    build: ./frontend

  cocina:
    build: ./cocina-service
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306"]

  plaza:
    build: ./plaza-service
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306"]

  receta:
    build: ./receta-service
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306"]

  bodega:
    build: ./bodega-service
    links:
      - mysql:mysql
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306"]

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - cocina
      - plaza
      - receta
      - bodega
      
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: 'almuerzo_gratis'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3307:3306"
    expose:
      - '3307'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: